name: Lottie Flutter
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze_and_test:
    name: Flutter analyze
    strategy:
      matrix:
        flutter: ['stable', 'dev']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: docker://cirrusci/flutter:stable
        with:
          entrypoint: update_goldens.sh